package suike.suikerawore;

import java.io.File;

import suike.suikerawore.asm.*;
import suike.suikerawore.proxy.*;
import suike.suikerawore.config.*;
import suike.suikerawore.expand.*;
import suike.suikerawore.event.Event;
import suike.suikerawore.item.ItemBase;
import suike.suikerawore.recipe.Recipe;
import suike.suikerawore.oredict.OreDict;
import suike.suikerawore.expand.ModEnchantmentHelper;

import net.minecraft.client.Minecraft;

import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.SidedProxy;
import net.minecraftforge.fml.common.FMLCommonHandler;
import net.minecraftforge.fml.common.event.FMLConstructionEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPostInitializationEvent;
import net.minecraftforge.fml.common.event.FMLLoadCompleteEvent;

@Mod(
    modid = SuiKe.MODID, name = SuiKe.NAME, version = SuiKe.VERSION,
    dependencies = "before:jei;"
)
public class SuiKe {

    public static final String MODID = "suikerawore";
    public static final String NAME = "Raw_Ore";
    public static final String VERSION = "1.5.3"; /// 已更新 1.5.2

    public static boolean isServer;
    public static boolean isZhCn = false;

    @Mod.Instance
    public static SuiKe instance;
    public SuiKe() { instance = this; }

    @SidedProxy(
        clientSide = "suike.suikerawore.proxy.ClientProxy",
        serverSide = "suike.suikerawore.proxy.CommonProxy"
    )
    public static CommonProxy proxy;

    @Mod.EventHandler
    public void Construction(FMLConstructionEvent event) {
        isServer = !FMLCommonHandler.instance().getSide().isClient();
    }

    @Mod.EventHandler
    public static void PreInit(FMLPreInitializationEvent event) {
        if (!isServer) {
            String language = Minecraft.getMinecraft().getLanguageManager().getCurrentLanguage().getLanguageCode();
            isZhCn = (language.equals("zh_cn") || language.equals("zh_tw") || language.equals("zh_hk"));
            模组简介(event);
        }
        Event.register();
    }

    // @Mod.EventHandler
    // public static void Init(FMLInitializationEvent event) {}

    // @Mod.EventHandler
    // public static void PostInit(FMLPostInitializationEvent event) {}

    @Mod.EventHandler
    public void LoadComplete(FMLLoadCompleteEvent event) {
        ASMData.cleanup();
        /*联动矿词*/OreDict.oreDictExpand();
        /*卸载事件*/Event.unregister();
        /*注册物品*/ItemBase.registerItems();
        /*重载模型*/SuiKe.proxy.reloadAllModels();
        /*矿词*/OreDict.oreDictAdd();
        /*配方*/Recipe.register();
        /*联动*/Expand.expand();
        /*初始化附魔*/ModEnchantmentHelper.initHelper();
        /*重载模型*/SuiKe.proxy.register();
    }

    private static void 模组简介(FMLPreInitializationEvent event) {
        event.getModMetadata().autogenerated = false;
        event.getModMetadata().url = "";
        event.getModMetadata().updateUrl = "";
        event.getModMetadata().logoFile = "assets/suikerawore/textures/gui/ico.png";

        if (SuiKe.isZhCn) {
            event.getModMetadata().name = "§e§o粗矿";
            event.getModMetadata().credits = "\n"
                    + "--------------------------------------------------" + "\n"
                    + "§d模组作者: sui_ke" + "\n"
                    + "--------------------------------------------------" + "\n"
                    + "§3感谢\"MC百科\"和所有的百科编辑员;" + "\n"
                    + "§e感谢sddsd2332帮助本模组兼容数字型采矿机" + "\n"
                    + "§e感谢:" + "\n"
                    + "§e - 御影; Noble; 镜野七罪ご; " + "\n"
                    + "--------------------------------------------------" + "\n"
                    + "§e相关链接:" + "\n"
                    + "§3MC百科: https://www.mcmod.cn/class/14517.html" + "\n"
                    + "§aModrinth: https://modrinth.com/mod/rawore_on_1.12.2" + "\n"
                    + "§6CurseForge: https://www.curseforge.com/minecraft/mc-mods/rawore-on-1-12-2" + "\n"
                    + "--------------------------------------------------" + "\n";
        } else {
            event.getModMetadata().name = "§e§oraw_Ore";
            event.getModMetadata().credits = "\n"
                    + "--------------------------------------------------" + "\n"
                    + "§dMod author: sui_ke" + "\n"
                    + "--------------------------------------------------" + "\n"
                    + "§3Thanks to MC百科 and all the MC百科 editors;" + "\n"
                    + "§eThanks to sddsd2332 for making this mod compatible with Digital Miner." + "\n"
                    + "§eThanks:" + "\n"
                    + "§e - 御影; Noble; 镜野七罪ご" + "\n"
                    + "--------------------------------------------------" + "\n"
                    + "§eRelated links:" + "\n"
                    + "§3MC百科: https://www.mcmod.cn/class/14517.html" + "\n"
                    + "§aModrinth: https://modrinth.com/mod/rawore_on_1.12.2" + "\n"
                    + "§6CurseForge: https://www.curseforge.com/minecraft/mc-mods/rawore-on-1-12-2" + "\n"
                    + "--------------------------------------------------" + "\n";
        }
    }
}