package suike.suikerawore;

import java.io.File;

import suike.suikerawore.item.*;
import suike.suikerawore.proxy.*;
import suike.suikerawore.config.*;
import suike.suikerawore.recipe.Recipe;
import suike.suikerawore.expand.Expand;
import suike.suikerawore.expand.Examine;
import suike.suikerawore.oredict.OreDict;

import net.minecraft.client.Minecraft;

import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.SidedProxy;
import net.minecraftforge.fml.common.FMLCommonHandler;
import net.minecraftforge.fml.common.event.FMLConstructionEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPostInitializationEvent;

@Mod(modid = SuiKe.MODID, name = SuiKe.NAME, version = SuiKe.VERSION)
public class SuiKe {

    public static final String MODID = "suikerawore";
    public static final String NAME = "§e1.12.2的粗矿";
    public static final String VERSION = "1.4.60"; // 已更新 1.4.59
    public static final String CLIENT_PROXY = "suike.suikerawore.proxy.ClientProxy";
    public static final String COMMON_PROXY = "suike.suikerawore.proxy.CommonProxy";

    public static boolean server = true;
    public static boolean isZhCn = false;

    @Mod.Instance
    public static SuiKe instance;

    @SidedProxy(clientSide = CLIENT_PROXY, serverSide = COMMON_PROXY)
    public static CommonProxy proxy;

    //@Mod.EventHandler
    //public void Construction(FMLConstructionEvent event) {}

    @Mod.EventHandler
    public static void PreInit(FMLPreInitializationEvent event) {
        //检查是否是服务器
        if (FMLCommonHandler.instance().getSide().isClient()) {
            server = false;

            String language = Minecraft.getMinecraft().getLanguageManager().getCurrentLanguage().getLanguageCode();
            isZhCn = (language.equals("zh_cn") || language.equals("zh_tw") || language.equals("zh_hk"));
        }

        /*读取配置文件*/Config.config(event);

        /*检查是否拥有联动模组*/Examine.examine();

        if (!server) {
            模组简介(event);
        }
    }

    //@Mod.EventHandler
    //public static void Init(FMLInitializationEvent event) {}

    @Mod.EventHandler
    public static void PostInit(FMLPostInitializationEvent event) {
        /*矿词*/OreDict.oreDict();

        /*隐藏不需要的物品*/ItemBase.removeItem();

        /*联动*/Expand.expand();

        /*配方*/Recipe.register();

        if (!server) {
            /*创造模式物品栏*/ItemBase.CreativeTabs();
            // suike.suikerawore.gui.ItemWarning.statrGui();
        }
    }

    private static void 模组简介(FMLPreInitializationEvent event) {
        String isLiteVersion = "";
        if (ConfigValue.LiteVersion) {
            isLiteVersion = isZhCn ? "-精简版" : "-Lite version";
        }

        event.getModMetadata().autogenerated = false;
        event.getModMetadata().url = "";
        event.getModMetadata().updateUrl = "";
        event.getModMetadata().logoFile = "assets/suikerawore/textures/gui/ico.png";

        if (SuiKe.isZhCn) {
            event.getModMetadata().name = "§e1.12.2的粗矿" + isLiteVersion;
            event.getModMetadata().credits = "\n"
                    + "--------------------------------------------------" + "\n"
                    + "§d模组作者: sui_ke" + "\n"
                    + "--------------------------------------------------" + "\n"
                    + "§3感谢\"MC百科\"和所有的百科编辑员;" + "\n"
                    + "§e感谢sddsd2332帮助本模组兼容数字型采矿机" + "\n"
                    + "§e感谢:" + "\n"
                    + "§e - 御影; Noble; 镜野七罪ご; " + "\n"
                    + "--------------------------------------------------" + "\n"
                    + "§e相关链接:" + "\n"
                    + "§3MC百科: https://www.mcmod.cn/class/14517.html" + "\n"
                    + "§aModrinth: https://modrinth.com/mod/rawore_on_1.12.2" + "\n"
                    + "§6CurseForge: https://www.curseforge.com/minecraft/mc-mods/rawore-on-1-12-2" + "\n"
                    + "--------------------------------------------------" + "\n";
        } else {
            event.getModMetadata().name = "§erawOre_on_1.12.2" + isLiteVersion;
            event.getModMetadata().credits = "\n"
                    + "--------------------------------------------------" + "\n"
                    + "§dMod author: sui_ke" + "\n"
                    + "--------------------------------------------------" + "\n"
                    + "§3Thanks to MC百科 and all the MC百科 editors;" + "\n"
                    + "§eThanks to sddsd2332 for making this mod compatible with Digital Miner." + "\n"
                    + "§eThanks:" + "\n"
                    + "§e - 御影; Noble; 镜野七罪ご" + "\n"
                    + "--------------------------------------------------" + "\n"
                    + "§eRelated links:" + "\n"
                    + "§3MC百科: https://www.mcmod.cn/class/14517.html" + "\n"
                    + "§aModrinth: https://modrinth.com/mod/rawore_on_1.12.2" + "\n"
                    + "§6CurseForge: https://www.curseforge.com/minecraft/mc-mods/rawore-on-1-12-2" + "\n"
                    + "--------------------------------------------------" + "\n";
        }
    }
}