package suike.suikerawore;

import java.util.List;
import java.util.ArrayList;

import suike.suikerawore.item.*;
import suike.suikerawore.proxy.*;
import suike.suikerawore.config.*;
import suike.suikerawore.recipe.Recipe;
import suike.suikerawore.expand.Expand;
import suike.suikerawore.expand.Examine;
import suike.suikerawore.oredictionary.OreDict;

import net.minecraft.client.Minecraft;
import net.minecraft.util.ResourceLocation;

import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.Mod.Instance;
import net.minecraftforge.fml.common.Mod.EventHandler;
import net.minecraftforge.fml.common.SidedProxy;
import net.minecraftforge.fml.common.FMLCommonHandler;
import net.minecraftforge.fml.common.event.FMLConstructionEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPostInitializationEvent;
import net.minecraftforge.fml.common.eventhandler.EventPriority;
import net.minecraftforge.fml.common.eventhandler.SubscribeEvent;
import net.minecraftforge.client.event.TextureStitchEvent;

@Mod(modid = SuiKe.MODID, name = SuiKe.NAME, version = SuiKe.VERSION)
@Mod.EventBusSubscriber
public class SuiKe {

    public static final String MODID = "suikerawore";
    public static final String NAME = "§e1.12.2的粗矿";
    public static final String VERSION = "1.4.44";
    public static final String ACCEPTED_VERSIONS = "[1.12.2]";
    public static final String CLIENT_PROXY = "suike.suikerawore.proxy.ClientProxy";
    public static final String COMMON_PROXY = "suike.suikerawore.proxy.CommonProxy";

    public static boolean server = true;
    public static boolean isZhCn;

    @Instance
    public static SuiKe instance;

    @SidedProxy(clientSide = CLIENT_PROXY, serverSide = COMMON_PROXY)
    public static CommonProxy proxy;

    //@Mod.EventHandler
    //public void Construction(FMLConstructionEvent event) {}

    @Mod.EventHandler
    public static void PreInit(FMLPreInitializationEvent event) {
        if (FMLCommonHandler.instance().getSide().isClient()) {
        //检查是否是服务器
            server = false;

            String language = Minecraft.getMinecraft().getLanguageManager().getCurrentLanguage().getLanguageCode();
            isZhCn = language.equals("zh_cn") || language.equals("zh_tw");

            模组简介(event);
        }

        /*读取配置文件*/Config.config(event);

        /*检查是否拥有联动模组*/Examine.examine();
    }

    //@EventHandler
    //public static void Init(FMLInitializationEvent event) {}

    @EventHandler
    public static void PostInit(FMLPostInitializationEvent event) {
        /*矿词*/OreDict.oreDict();

        //注册物品
        //ItemBase.registerItem();
        OreDict.oreDictRawAdd();

        /*联动*/Expand.expand();

        /*配方*/Recipe.register();

        /*隐藏不需要的物品*/ItemBase.removeItem();

        if (!server && !ConfigValue.LiteVersion) {
            /*创建物品栏*/rawOreTabs.Inventory();
        }
    }

    private static void 模组简介(FMLPreInitializationEvent event) {
        event.getModMetadata().autogenerated = false;
        event.getModMetadata().name = "§e" + NAME;
        event.getModMetadata().url = "";
        event.getModMetadata().updateUrl = "";
        event.getModMetadata().logoFile = "assets/suikerawore/textures/gui/ico.png";

        if (SuiKe.isZhCn) {
            event.getModMetadata().name = "§e1.12.2的粗矿";
            event.getModMetadata().credits = "\n"
                    + "--------------------------------------------------" + "\n"
                    + "§d模组作者: sui_ke" + "\n"
                    + "--------------------------------------------------" + "\n"
                    + "§3感谢\"MC百科\"和所有的百科编辑员;" + "\n"
                    + "§5感谢ChatGPT;" + "\n"
                    + "§e感谢sddsd2332帮助本模组兼容数字型采矿机" + "\n"
                    + "§e感谢:" + "\n"
                    + "§e - 御影; Noble; 镜野七罪ご; " + "\n"
                    + "§c发现的严重漏洞" + "   §r- 按提交顺序" + "\n"
                    + "--------------------------------------------------" + "\n"
                    + "§e相关链接:" + "\n"
                    + "§3MC百科: https://www.mcmod.cn/class/14517.html" + "\n"
                    + "§aModrinth: https://modrinth.com/mod/rawore_on_1.12.2" + "\n"
                    + "§6CurseForge: https://www.curseforge.com/minecraft/mc-mods/rawore-on-1-12-2" + "\n"
                    + "§a更新日志: https://modrinth.com/mod/rawore_on_1.12.2/changelog" + "\n"
                    + "--------------------------------------------------" + "\n"
                    + "§c本模组只发布在 \"MC百科\" , \"curseforge\" 和 \"Modrinth\" ," + "\n"
                    + "§c其他网站上的文件出问题后果自负!" + "\n"
                    + "--------------------------------------------------" + "\n";
        } else {
            event.getModMetadata().name = "§erawOre_on_1.12.2";
            event.getModMetadata().credits = "\n"
                    + "--------------------------------------------------" + "\n"
                    + "§dMod author: sui_ke" + "\n"
                    + "--------------------------------------------------" + "\n"
                    + "§3Thanks to MC百科 and all the MC百科 editors;" + "\n"
                    + "§5Thanks to ChatGPT;" + "\n"
                    + "§eThanks to sddsd2332 for making this mod compatible with Digital Miner." + "\n"
                    + "§eThanks:" + "\n"
                    + "§e - 御影; Noble; 镜野七罪ご" + "\n"
                    + "§cDiscovered critical bugs" + "   §r- In order of submission" + "\n"
                    + "--------------------------------------------------" + "\n"
                    + "§eRelated links:" + "\n"
                    + "§3MC百科: https://www.mcmod.cn/class/14517.html" + "\n"
                    + "§aModrinth: https://modrinth.com/mod/rawore_on_1.12.2" + "\n"
                    + "§6CurseForge: https://www.curseforge.com/minecraft/mc-mods/rawore-on-1-12-2" + "\n"
                    + "§aChangelog: https://modrinth.com/mod/rawore_on_1.12.2/changelog" + "\n"
                    + "--------------------------------------------------" + "\n"
                    + "§cThis mod is only released on \"MC百科\" , \"curseforge\" and \"Modrinth\"," + "\n"
                    + "§cFiles on other websites are not necessarily safe!" + "\n"
                    + "§cIf something goes wrong, you will be at your own risk!" + "\n"
                    + "--------------------------------------------------" + "\n";
        }
    }

    //@SubscribeEvent
    public static void onTextureStitchPre(TextureStitchEvent.Pre event) {
        List<String> textureNameList = new ArrayList<>();

        textureNameList.add("items/rawore/raw_gold");
        textureNameList.add("items/rawore/raw_iron");
        textureNameList.add("items/rawore/raw_copper");
        textureNameList.add("items/rawore/raw_tin");
        textureNameList.add("items/rawore/raw_zinc");
        textureNameList.add("items/rawore/raw_lead");
        textureNameList.add("items/rawore/raw_silver");
        textureNameList.add("items/rawore/raw_cobalt");
        textureNameList.add("items/rawore/raw_osmium");
        textureNameList.add("items/rawore/raw_nickel");
        textureNameList.add("items/rawore/raw_iridium");
        textureNameList.add("items/rawore/raw_uranium");
        textureNameList.add("items/rawore/raw_gallium");
        textureNameList.add("items/rawore/raw_titanium");
        textureNameList.add("items/rawore/raw_platinum");
        textureNameList.add("items/rawore/raw_tungsten");
        textureNameList.add("items/rawore/raw_aluminium");
        textureNameList.add("items/rawore/raw_magnesium");
        textureNameList.add("items/rawore/raw_lithium");
        textureNameList.add("items/rawore/raw_thorium");
        textureNameList.add("items/rawore/raw_boron");
        textureNameList.add("items/rawore/raw_vanadium");
        textureNameList.add("items/rawore/raw_cadmium");
        textureNameList.add("items/rawore/raw_manganese");
        textureNameList.add("items/rawore/raw_germanium");
        textureNameList.add("items/rawore/raw_chromium");
        textureNameList.add("items/rawore/raw_arsenic");
        textureNameList.add("items/rawore/raw_ardite");
        textureNameList.add("items/rawore/raw_cerulean");
        textureNameList.add("items/rawore/raw_moonstone");
        textureNameList.add("items/rawore/raw_octine");
        textureNameList.add("items/rawore/raw_syrmorite");
        textureNameList.add("items/rawore/raw_cinnabar");
        textureNameList.add("items/rawore/raw_vulcanite");
        textureNameList.add("items/rawore/raw_chasmium");
        textureNameList.add("items/rawore/raw_rosegold");

        textureNameList.add("items/ingot/copper_ingot");
        textureNameList.add("items/ingot/tin_ingot");
        textureNameList.add("items/ingot/zinc_ingot");
        textureNameList.add("items/ingot/lead_ingot");
        textureNameList.add("items/ingot/silver_ingot");
        textureNameList.add("items/ingot/cobalt_ingot");
        textureNameList.add("items/ingot/osmium_ingot");
        textureNameList.add("items/ingot/nickel_ingot");
        textureNameList.add("items/ingot/iridium_ingot");
        textureNameList.add("items/ingot/uranium_ingot");
        textureNameList.add("items/ingot/gallium_ingot");
        textureNameList.add("items/ingot/titanium_ingot");
        textureNameList.add("items/ingot/platinum_ingot");
        textureNameList.add("items/ingot/tungsten_ingot");
        textureNameList.add("items/ingot/aluminium_ingot");
        textureNameList.add("items/ingot/magnesium_ingot");
        textureNameList.add("items/ingot/lithium_ingot");
        textureNameList.add("items/ingot/thorium_ingot");
        textureNameList.add("items/ingot/boron_ingot");
        textureNameList.add("items/ingot/vanadium_ingot");
        textureNameList.add("items/ingot/cadmium_ingot");
        textureNameList.add("items/ingot/manganese_ingot");
        textureNameList.add("items/ingot/germanium_ingot");
        textureNameList.add("items/ingot/chromium_ingot");
        textureNameList.add("items/ingot/arsenic_ingot");

        textureNameList.add("blocks/rawore/raw_gold_block");
        textureNameList.add("blocks/rawore/raw_iron_block");
        textureNameList.add("blocks/rawore/raw_copper_block");
        textureNameList.add("blocks/rawore/raw_tin_block");
        textureNameList.add("blocks/rawore/raw_zinc_block");
        textureNameList.add("blocks/rawore/raw_lead_block");
        textureNameList.add("blocks/rawore/raw_silver_block");
        textureNameList.add("blocks/rawore/raw_cobalt_block");
        textureNameList.add("blocks/rawore/raw_osmium_block");
        textureNameList.add("blocks/rawore/raw_nickel_block");
        textureNameList.add("blocks/rawore/raw_iridium_block");
        textureNameList.add("blocks/rawore/raw_uranium_block");
        textureNameList.add("blocks/rawore/raw_gallium_block");
        textureNameList.add("blocks/rawore/raw_titanium_block");
        textureNameList.add("blocks/rawore/raw_platinum_block");
        textureNameList.add("blocks/rawore/raw_tungsten_block");
        textureNameList.add("blocks/rawore/raw_aluminium_block");
        textureNameList.add("blocks/rawore/raw_magnesium_block");
        textureNameList.add("blocks/rawore/raw_lithium_block");
        textureNameList.add("blocks/rawore/raw_thorium_block");
        textureNameList.add("blocks/rawore/raw_boron_block");
        textureNameList.add("blocks/rawore/raw_vanadium_block");
        textureNameList.add("blocks/rawore/raw_cadmium_block");
        textureNameList.add("blocks/rawore/raw_manganese_block");
        textureNameList.add("blocks/rawore/raw_germanium_block");
        textureNameList.add("blocks/rawore/raw_chromium_block");
        textureNameList.add("blocks/rawore/raw_arsenic_block");
        textureNameList.add("blocks/rawore/raw_ardite_block");
        textureNameList.add("blocks/rawore/raw_cerulean_block");
        textureNameList.add("blocks/rawore/raw_moonstone_block");
        textureNameList.add("blocks/rawore/raw_octine_block");
        textureNameList.add("blocks/rawore/raw_syrmorite_block");
        textureNameList.add("blocks/rawore/raw_cinnabar_block");
        textureNameList.add("blocks/rawore/raw_vulcanite_block");
        textureNameList.add("blocks/rawore/raw_chasmium_block");
        textureNameList.add("blocks/rawore/raw_rosegold_block");

        textureNameList.add("blocks/blocks/copper_block");
        textureNameList.add("blocks/blocks/tin_block");
        textureNameList.add("blocks/blocks/zinc_block");
        textureNameList.add("blocks/blocks/lead_block");
        textureNameList.add("blocks/blocks/silver_block");
        textureNameList.add("blocks/blocks/cobalt_block");
        textureNameList.add("blocks/blocks/osmium_block");
        textureNameList.add("blocks/blocks/nickel_block");
        textureNameList.add("blocks/blocks/iridium_block");
        textureNameList.add("blocks/blocks/uranium_block");
        textureNameList.add("blocks/blocks/gallium_block");
        textureNameList.add("blocks/blocks/titanium_block");
        textureNameList.add("blocks/blocks/platinum_block");
        textureNameList.add("blocks/blocks/tungsten_block");
        textureNameList.add("blocks/blocks/aluminium_block");
        textureNameList.add("blocks/blocks/magnesium_block");
        textureNameList.add("blocks/blocks/lithium_block");
        textureNameList.add("blocks/blocks/thorium_block");
        textureNameList.add("blocks/blocks/boron_block");
        textureNameList.add("blocks/blocks/vanadium_block");
        textureNameList.add("blocks/blocks/cadmium_block");
        textureNameList.add("blocks/blocks/manganese_block");
        textureNameList.add("blocks/blocks/germanium_block");
        textureNameList.add("blocks/blocks/chromium_block");
        textureNameList.add("blocks/blocks/arsenic_block");

        for (String textureName : textureNameList) {
            event.getMap().registerSprite(new ResourceLocation(MODID, textureName));
        }
    }
}